amazon:
  service: S3
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] || 'sample' %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] || 'sample' %>
  region: <%= ENV['AWS_REGION'] || 'us-east-1' %>
  bucket: <%= ENV['S3_BUCKET'] || 'dev-bucket' %>